In [1]:
import pandas as pd
df=pd.read_parquet("data/Benign-Monday-no-metadata.parquet")
df.head()

,Protocol,Flow Duration,Total Fwd Packets,Total Backward Packets,Fwd Packets Length Total,Bwd Packets Length Total,Fwd Packet Length Max,Fwd Packet Length Min,Fwd Packet Length Mean,Fwd Packet Length Std,...,Fwd Seg Size Min,Active Mean,Active Std,Active Max,Active Min,Idle Mean,Idle Std,Idle Max,Idle Min,Label
0,6,4,2,0,12,0,6,6,6.00000,0.000000,...,20,0.0,0.0,0,0,0.0,0.0,0,0,Benign
1,6,1,2,0,12,0,6,6,6.00000,0.000000,...,20,0.0,0.0,0,0,0.0,0.0,0,0,Benign
2,6,3,2,0,12,0,6,6,6.00000,0.000000,...,20,0.0,0.0,0,0,0.0,0.0,0,0,Benign
3,6,1,2,0,12,0,6,6,6.00000,0.000000,...,20,0.0,0.0,0,0,0.0,0.0,0,0,Benign
4,6,609,7,4,484,414,233,0,69.14286,111.967896,...,20,0.0,0.0,0,0,0.0,0.0,0,0,Benign

In [2]:
df.shape

(458831, 78)

In [3]:
df.columns

Index(['Protocol', 'Flow Duration', 'Total Fwd Packets',
       'Total Backward Packets', 'Fwd Packets Length Total',
       'Bwd Packets Length Total', 'Fwd Packet Length Max',
       'Fwd Packet Length Min', 'Fwd Packet Length Mean',
       'Fwd Packet Length Std', 'Bwd Packet Length Max',
       'Bwd Packet Length Min', 'Bwd Packet Length Mean',
       'Bwd Packet Length Std', 'Flow Bytes/s', 'Flow Packets/s',
       'Flow IAT Mean', 'Flow IAT Std', 'Flow IAT Max', 'Flow IAT Min',
       'Fwd IAT Total', 'Fwd IAT Mean', 'Fwd IAT Std', 'Fwd IAT Max',
       'Fwd IAT Min', 'Bwd IAT Total', 'Bwd IAT Mean', 'Bwd IAT Std',
       'Bwd IAT Max', 'Bwd IAT Min', 'Fwd PSH Flags', 'Bwd PSH Flags',
       'Fwd URG Flags', 'Bwd URG Flags', 'Fwd Header Length',
       'Bwd Header Length', 'Fwd Packets/s', 'Bwd Packets/s',
       'Packet Length Min', 'Packet Length Max', 'Packet Length Mean',
       'Packet Length Std', 'Packet Length Variance', 'FIN Flag Count',
       'SYN Flag Count', 'RST Flag Count', 'PSH Flag Count', 'ACK Flag Count',
       'URG Flag Count', 'CWE Flag Count', 'ECE Flag Count', 'Down/Up Ratio',
       'Avg Packet Size', 'Avg Fwd Segment Size', 'Avg Bwd Segment Size',
       'Fwd Avg Bytes/Bulk', 'Fwd Avg Packets/Bulk', 'Fwd Avg Bulk Rate',
       'Bwd Avg Bytes/Bulk', 'Bwd Avg Packets/Bulk', 'Bwd Avg Bulk Rate',
       'Subflow Fwd Packets', 'Subflow Fwd Bytes', 'Subflow Bwd Packets',
       'Subflow Bwd Bytes', 'Init Fwd Win Bytes', 'Init Bwd Win Bytes',
       'Fwd Act Data Packets', 'Fwd Seg Size Min', 'Active Mean', 'Active Std',
       'Active Max', 'Active Min', 'Idle Mean', 'Idle Std', 'Idle Max',
       'Idle Min', 'Label'],
      dtype='str')

In [4]:
df["Label"]

0         Benign
1         Benign
2         Benign
3         Benign
4         Benign
           ...
458826    Benign
458827    Benign
458828    Benign
458829    Benign
458830    Benign
Name: Label, Length: 458831, dtype: category
Categories (1, str): ['Benign']

In [5]:
df["Label"].value_counts()

Label
Benign    458831
Name: count, dtype: int64

In [6]:
df_attack = pd.read_parquet("data/DoS-Wednesday-no-metadata.parquet")

In [7]:
df_attack["Label"].value_counts()

Label
Benign              391235
DoS Hulk            172846
DoS GoldenEye        10286
DoS slowloris         5385
DoS Slowhttptest      5228
Heartbleed              11
Name: count, dtype: int64

In [10]:
df_attack.shape

(584991, 78)

In [11]:
df.dtypes

Protocol                        int8
Flow Duration                  int32
Total Fwd Packets              int32
Total Backward Packets         int32
Fwd Packets Length Total       int32
                              ...
Idle Mean                    float32
Idle Std                     float32
Idle Max                       int32
Idle Min                       int32
Label                       category
Length: 78, dtype: object

In [13]:
df.duplicated().sum()

np.int64(0)

In [12]:
df.isnull().sum().sum()

np.int64(0)

In [14]:
df_attack.isnull().sum().sum()

np.int64(0)

In [15]:
df.iloc[0]

Protocol                         6
Flow Duration                    4
Total Fwd Packets                2
Total Backward Packets           0
Fwd Packets Length Total        12
                             ...
Idle Mean                      0.0
Idle Std                       0.0
Idle Max                         0
Idle Min                         0
Label                       Benign
Name: 0, Length: 78, dtype: object

In [16]:
files = [
    "data/Benign-Monday-no-metadata.parquet",
    "data/Botnet-Friday-no-metadata.parquet",
    "data/Bruteforce-Tuesday-no-metadata.parquet",
    "data/DDoS-Friday-no-metadata.parquet",
    "data/DoS-Wednesday-no-metadata.parquet",
    "data/Infiltration-Thursday-no-metadata.parquet",
    "data/Portscan-Friday-no-metadata.parquet",
    "data/WebAttacks-Thursday-no-metadata.parquet"
]

In [18]:
datasets=[pd.read_parquet(file) for file in files]

In [19]:
len(datasets)

8

In [21]:
for file, data in zip(files, datasets):
    print(file, data.shape)

data/Benign-Monday-no-metadata.parquet (458831, 78)
data/Botnet-Friday-no-metadata.parquet (176038, 78)
data/Bruteforce-Tuesday-no-metadata.parquet (389714, 78)
data/DDoS-Friday-no-metadata.parquet (221264, 78)
data/DoS-Wednesday-no-metadata.parquet (584991, 78)
data/Infiltration-Thursday-no-metadata.parquet (207630, 78)
data/Portscan-Friday-no-metadata.parquet (119522, 78)
data/WebAttacks-Thursday-no-metadata.parquet (155820, 78)

In [22]:
for file, data in zip(files, datasets):
    print("\n", file)
    print(data["Label"].value_counts())

 data/Benign-Monday-no-metadata.parquet
Label
Benign    458831
Name: count, dtype: int64

 data/Botnet-Friday-no-metadata.parquet
Label
Benign    174601
Bot         1437
Name: count, dtype: int64

 data/Bruteforce-Tuesday-no-metadata.parquet
Label
Benign         380564
FTP-Patator      5931
SSH-Patator      3219
Name: count, dtype: int64

 data/DDoS-Friday-no-metadata.parquet
Label
DDoS      128014
Benign     93250
Name: count, dtype: int64

 data/DoS-Wednesday-no-metadata.parquet
Label
Benign              391235
DoS Hulk            172846
DoS GoldenEye        10286
DoS slowloris         5385
DoS Slowhttptest      5228
Heartbleed              11
Name: count, dtype: int64

 data/Infiltration-Thursday-no-metadata.parquet
Label
Benign          207594
Infiltration        36
Name: count, dtype: int64

 data/Portscan-Friday-no-metadata.parquet
Label
Benign      117566
PortScan      1956
Name: count, dtype: int64

 data/WebAttacks-Thursday-no-metadata.parquet
Label
Benign                        153677
Web Attack � Brute Force        1470
Web Attack � XSS                 652
Web Attack � Sql Injection        21
Name: count, dtype: int64

In [23]:
for file, data in zip(files, datasets):
    print("\n", file)
    print(data["Label"].unique())

 data/Benign-Monday-no-metadata.parquet
['Benign']
Categories (1, str): ['Benign']

 data/Botnet-Friday-no-metadata.parquet
['Benign', 'Bot']
Categories (2, str): ['Benign', 'Bot']

 data/Bruteforce-Tuesday-no-metadata.parquet
['Benign', 'FTP-Patator', 'SSH-Patator']
Categories (3, str): ['Benign', 'FTP-Patator', 'SSH-Patator']

 data/DDoS-Friday-no-metadata.parquet
['Benign', 'DDoS']
Categories (2, str): ['Benign', 'DDoS']

 data/DoS-Wednesday-no-metadata.parquet
['Benign', 'DoS slowloris', 'DoS Slowhttptest', 'DoS Hulk', 'DoS GoldenEye', 'Heartbleed']
Categories (6, str): ['Benign', 'DoS GoldenEye', 'DoS Hulk', 'DoS Slowhttptest', 'DoS slowloris', 'Heartbleed']

 data/Infiltration-Thursday-no-metadata.parquet
['Benign', 'Infiltration']
Categories (2, str): ['Benign', 'Infiltration']

 data/Portscan-Friday-no-metadata.parquet
['Benign', 'PortScan']
Categories (2, str): ['Benign', 'PortScan']

 data/WebAttacks-Thursday-no-metadata.parquet
['Benign', 'Web Attack � Brute Force', 'Web Attack � XSS', 'Web Attack � Sql Injection']
Categories (4, str): ['Benign', 'Web Attack � Brute Force', 'Web Attack � Sql Injection', 'Web Attack � XSS']

In [24]:
df_attack["target"] = (df_attack["Label"] != "Benign").astype(int)

In [25]:
df_attack[["Label", "target"]].head(10)

    Label  target
0  Benign       0
1  Benign       0
2  Benign       0
3  Benign       0
4  Benign       0
5  Benign       0
6  Benign       0
7  Benign       0
8  Benign       0
9  Benign       0

In [26]:
df_attack["target"].value_counts()

target
0    391235
1    193756
Name: count, dtype: int64

In [27]:
for data in datasets:
    data["target"] = (data["Label"] != "Benign").astype(int)

In [30]:
for file, data in zip(files, datasets):
    print("\n", file)
    print(data["target"].value_counts())

 data/Benign-Monday-no-metadata.parquet
target
0    458831
Name: count, dtype: int64

 data/Botnet-Friday-no-metadata.parquet
target
0    174601
1      1437
Name: count, dtype: int64

 data/Bruteforce-Tuesday-no-metadata.parquet
target
0    380564
1      9150
Name: count, dtype: int64

 data/DDoS-Friday-no-metadata.parquet
target
1    128014
0     93250
Name: count, dtype: int64

 data/DoS-Wednesday-no-metadata.parquet
target
0    391235
1    193756
Name: count, dtype: int64

 data/Infiltration-Thursday-no-metadata.parquet
target
0    207594
1        36
Name: count, dtype: int64

 data/Portscan-Friday-no-metadata.parquet
target
0    117566
1      1956
Name: count, dtype: int64

 data/WebAttacks-Thursday-no-metadata.parquet
target
0    153677
1      2143
Name: count, dtype: int64

In [31]:
df_all = pd.concat(datasets, ignore_index=True)

In [32]:
df_all.shape

(2313810, 79)

In [34]:
df_all["target"].value_counts()

target
0    1977318
1     336492
Name: count, dtype: int64

In [36]:
import numpy as np

np.isinf(df_all.select_dtypes(include=np.number)).sum().sum()

np.int64(0)

In [37]:
X = df_all.drop(columns=["Label", "target"])

In [38]:
y = df_all["target"]

In [39]:
X.shape

(2313810, 77)

In [40]:
y.shape

(2313810,)

In [42]:
from sklearn.model_selection import train_test_split

In [46]:
X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42,
    stratify=y
)

In [47]:
X_train.shape

(1851048, 77)

In [48]:
print(X_train.shape)
print(X_test.shape)
print(y_train.shape)
print(y_test.shape)

(1851048, 77)
(462762, 77)
(1851048,)
(462762,)

In [49]:
from sklearn.ensemble import RandomForestClassifier

In [50]:
rf_model = RandomForestClassifier(
    n_estimators=100,
    random_state=42,
    n_jobs=-1
)

In [51]:
#train the model
rf_model.fit(X_train, y_train)

RandomForestClassifier(n_jobs=-1, random_state=42)

In [53]:
y_pred=rf_model.predict(X_test)

In [54]:
y_pred[:20]

array([0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0])

In [55]:
from sklearn.metrics import confusion_matrix

In [56]:
cm = confusion_matrix(y_test, y_pred)
cm

array([[395276,    188],
       [   348,  66950]])

In [57]:
from sklearn.metrics import classification_report

print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00    395464
           1       1.00      0.99      1.00     67298

    accuracy                           1.00    462762
   macro avg       1.00      1.00      1.00    462762
weighted avg       1.00      1.00      1.00    462762

In [58]:
feature_importance = pd.Series(
    rf_model.feature_importances_,
    index=X_train.columns
)

feature_importance.sort_values(ascending=False).head(10)

Bwd Packet Length Std       0.081975
Bwd Packet Length Mean      0.073217
Avg Bwd Segment Size        0.071429
Packet Length Variance      0.071347
Bwd Packet Length Max       0.063241
Packet Length Std           0.044991
Bwd Packets Length Total    0.040493
Avg Packet Size             0.040410
Fwd IAT Std                 0.036261
Packet Length Mean          0.033048
dtype: float64

In [59]:
from xgboost import XGBClassifier

In [60]:
xgb_model = XGBClassifier(
    n_estimators=100,
    max_depth=8,
    learning_rate=0.1,
    random_state=42,
    n_jobs=-1,
    eval_metric="logloss"
)

In [61]:
xgb_model.fit(X_train, y_train)

XGBClassifier(base_score=None, booster=None, callbacks=None,
              colsample_bylevel=None, colsample_bynode=None,
              colsample_bytree=None, device=None, early_stopping_rounds=None,
              enable_categorical=False, eval_metric='logloss',
              feature_types=None, feature_weights=None, gamma=None,
              grow_policy=None, importance_type=None,
              interaction_constraints=None, learning_rate=0.1, max_bin=None,
              max_cat_threshold=None, max_cat_to_onehot=None,
              max_delta_step=None, max_depth=8, max_leaves=None,
              min_child_weight=None, missing=nan, monotone_constraints=None,
              multi_strategy=None, n_estimators=100, n_jobs=-1,
              num_parallel_tree=None, ...)

In [62]:
xgb_pred = xgb_model.predict(X_test)

In [63]:
from sklearn.metrics import classification_report

print(classification_report(y_test, xgb_pred))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00    395464
           1       1.00      1.00      1.00     67298

    accuracy                           1.00    462762
   macro avg       1.00      1.00      1.00    462762
weighted avg       1.00      1.00      1.00    462762

In [64]:
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score

print("Accuracy :", accuracy_score(y_test, xgb_pred))
print("Precision:", precision_score(y_test, xgb_pred))
print("Recall   :", recall_score(y_test, xgb_pred))
print("F1-score :", f1_score(y_test, xgb_pred))

Accuracy : 0.9991464294821096
Precision: 0.9974126778783958
Recall   : 0.9967160985467621
F1-score : 0.9970642665497328

In [65]:
import joblib

joblib.dump(xgb_model, "xgb_ids_model.pkl")

['xgb_ids_model.pkl']

In [66]:
import joblib

loaded_model = joblib.load("xgb_ids_model.pkl")

print(type(loaded_model))

<class 'xgboost.sklearn.XGBClassifier'>

In [67]:
feature_names = X_train.columns.tolist()

joblib.dump(feature_names, "feature_names.pkl")

['feature_names.pkl']

In [68]:

import os

print(os.path.getsize("xgb_ids_model.pkl") / (1024 * 1024), "MB")
print(os.path.getsize("feature_names.pkl") / 1024, "KB")

0.5342140197753906 MB
1.3935546875 KB